// Array con todos los juegos
// ACLARACIONES:
// La complejidad va de 1 a 5
// Hay juegos que tienen una cantidad fija de jugadores, por eso tienen lo mismo en jugadores minimos y máximos
const juegos = [
    { 
        nombre: "7 Wonders Duel",      
        img_1: "7 wonders duel 1.jfif",
        img_2: "7 wonders duel 2.jfif",
        img_3: "7 wonders duel 3.webp",
        img_4: "7 wonders duel 4.webp",
        img_5: "7 wonders duel 5.jfif",  
        link: "7_wonders_duel",
        descripcion: "7 Wonders Duel es un juego de mesa que combina estrategia, gestión de recursos y construcción de maravillas en una competición directa por la supremacía de tu civilización sobre la del oponente. Cada jugador es el líder de una civilización que construirá Estructuras y erigirá Maravillas. Las Estructuras y las Maravillas construidas por cada jugador componen su «ciudad». Existen 3 formas de ganar en 7 Wonders Duel: supremacía militar, supremacía científica y victoria civil. Tanto la supremacía militar como la supremacía científica pueden darse en cualquier momento, y hacen que la partida termine inmediatamente. Si al final de la tercera Era nadie ha conseguido ganar, los jugadores sumarán sus puntos de victoria y aquel que tenga más será el ganador.",
        jugadoresMinimos: 2, 
        jugadoresMaximos: 2, 
        duracionPartida: 30, 
        complejidad: 2, 
        precio: 75000 
    },
    { 
        nombre: "Ajedrez",             
        img_1: "ajedrez 1.webp",
        img_2: "ajedrez 2.webp", 
        img_3: "ajedrez 3.webp",              
        link: "ajedrez",
        descripcion: "El ajedrez es un juego de mesa estratégico entre dos jugadores, donde cada uno controla un ejército de piezas con el objetivo de capturar al rey del oponente. Se juega en un tablero cuadrado de 8x8 casillas, alternando colores claros y oscuros, lo que da un total de 64 escaques.",       
        jugadoresMinimos: 2, 
        jugadoresMaximos: 2, 
        duracionPartida: 20, 
        complejidad: 2,
        precio: 6000 
    },
    { 
        nombre: "Aventureros al tren", 
        img_1: "aventureros al tren 1.webp",
        img_2: "aventureros al tren 2.jpg",
        img_3: "aventureros al tren 3.jpg",
        img_4: "aventureros al tren 4.webp",
        link: "aventureros_al_tren", 
        descripcion: "Los jugadores acumulan cartas de ciertos tipos de vagones que les permiten conectar diferentes ciudades a lo largo y ancho del mapa de Estados Unidos. Mientras más largos son los recorridos, más puntos se ganan. Quienes consigan cumplir con sus Billetes de Destino, conectando dos ciudades lejanas, y quien consiga construir la ruta ferroviaria continua más larga, ganarán puntos adicionales.", 
        jugadoresMinimos: 2, 
        jugadoresMaximos: 5,
        duracionPartida: 60, 
        complejidad: 2, 
        precio: 98000 
    },
    { 
        nombre: "Azul",                
        img_1: "azul 1.jpg",
        img_2: "azul 2.webp",
        img_3: "azul 3.webp",
        img_4: "azul 4.webp",
        img_5: "azul 5.jpg",                
        link: "azul",
        descripcion: "Azul transporta a los jugadores a la época del rey Manuel I de Portugal, quien, fascinado por los azulejos de la Alhambra en España, decidió decorar su palacio en Évora con patrones similares. Cada jugador asume el rol de un artesano azulejero encargado de embellecer las paredes del palacio, combinando estética y estrategia en la colocación de los azulejos. El objetivo es obtener la mayor puntuación mediante la colocación estratégica de losetas de colores.",          
        jugadoresMinimos: 2, 
        jugadoresMaximos: 4, 
        duracionPartida: 30, 
        complejidad: 2, 
        precio: 90000 
    },
    {
        nombre: "Carcassonne",
        img_1: "carcassonne 1.jpg",
        img_2: "carcassonne 2.jpg",
        img_3: "carcassonne 3.jfif",
        link: "carcassonne",
        descripcion: "Carcassonne es un juego de mesa de colocación de losetas donde los jugadores construyen un paisaje medieval, compiten por controlar territorios y acumulan puntos. En cada turno, los jugadores toman una loseta al azar y la colocan en el tablero, asegurándose de que coincida con las características de las losetas adyacentes. Después de colocar una loseta, los jugadores pueden colocar un meeple en ella para reclamar un camino, ciudad, campo o monasterio. Los jugadores puntúan cuando completan estructuras. Por ejemplo, obtienen puntos por caminos y ciudades cerradas, y los meeples se devuelven para ser utilizados nuevamente en futuras construcciones. Al final del juego, se otorgan puntos adicionales por los campos controlados.",
        jugadoresMinimos: 2,
        jugadoresMaximos: 5,
        duracionPartida: 45,
        complejidad: 2,
        precio: 62000,
    },
    { 
        nombre: "Catan",               
        img_1: "catan 1.webp", 
        img_2: "catan 2.jpg",
        img_3: "catan 3.avif",
        img_4: "catan 4.jpg",              
        img_5: "catan 5.jpg",
        link: "catan",        
        descripcion: "Catan es un juego de mesa que combina estrategia, suerte y negociación. Los jugadores buscan colonizar una isla construyendo poblados, carreteras y ciudades. La premisa es sencilla, pero la estrategia es profunda. Los jugadores reciben cartas de recursos basadas en la posición de sus asentamientos iniciales y deben negociar estos recursos con otros jugadores. El lanzamiento de los dados al inicio de cada turno determina qué terrenos producen recursos, mezclando suerte y estrategia. El objetivo final es acumular puntos de victoria, construyendo carreteras más largas, más poblados, ciudades o logrando ciertas cartas de desarrollo especiales.",       
        jugadoresMinimos: 3, 
        jugadoresMaximos: 4, 
        duracionPartida: 60, 
        complejidad: 2, 
        precio: 92000 
    },
    { 
        nombre: "Damas",               
        img_1: "damas 1.webp",               
        img_2: "damas 2.jpg",
        img_3: "damas 3.webp",
        link: "damas",
        descripcion: "Las damas es un juego de mesa clásico para dos jugadores que combina estrategia, táctica y habilidad para capturar o bloquear las piezas del oponente. Las fichas se colocan inicialmente en las casillas oscuras de las filas más cercanas a cada jugador, y el objetivo principal es capturar todas las piezas del adversario o bloquear sus movimientos, impidiendo que puedan moverse.",               
        jugadoresMinimos: 2, 
        jugadoresMaximos: 2, 
        duracionPartida: 20, 
        complejidad: 1, 
        precio: 4000 
    },
    {
        nombre: "Kanagawa",            
        img_1: "kanagawa 1.webp",
        img_2: "kanagawa 2.jpg",
        img_3: "kanagawa 3.webp",
        img_4: "kanagawa 4.webp",        
        link: "kanagawa",      
        descripcion: "Kanagawa es un juego de mesa que combina estrategia y creatividad, permitiendo a los jugadores convertirse en maestros pintores en el taller de Katsushika Hokusai. El objetivo es acumular puntos de prestigio a través de la creación de paisajes y la gestión de tu estudio. Durante el juego, los jugadores deben elegir entre diferentes cartas de acción que les permiten pintar, mejorar sus técnicas y expandir su estudio. Cada turno, los jugadores tienen la oportunidad de diseñar su obra maestra mientras equilibran el desarrollo de su taller y la adquisición de técnicas.",      
        jugadoresMinimos: 2, 
        jugadoresMaximos: 4, 
        duracionPartida: 45, 
        complejidad: 2, 
        precio: 40000 
    },
    { 
        nombre: "King of New York",    
        img_1: "king of new york 1.webp",
        img_2: "king of new york 2.jpg",
        img_3: "king of new york 3.webp",
        img_4: "king of new york 4.webp",
        img_5: "king of new york 5.webp",
        link: "king_of_new_york",    
        descripcion: "King of New York es un juego de mesa de estrategia y combate donde los jugadores controlan monstruos colosales que buscan dominar la ciudad de Nueva York. A través de lanzamiento de dados, control de territorio y tácticas de ataque, cada jugador decide si se enfrenta a sus rivales directamente o si acumula poder para convertirse en el rey indiscutible. El objetivo es acumular 20 puntos de victoria o eliminar a todos los oponentes, utilizando habilidades especiales y adaptando la estrategia a cada situación.",
        jugadoresMinimos: 2, 
        jugadoresMaximos: 6, 
        duracionPartida: 40, 
        complejidad: 1, 
        precio: 150000 
    },
    { 
        nombre: "King of Tokyo",       
        img_1: "king of tokyo 1.webp",
        img_2: "king of tokyo 2.webp",
        img_3: "king of tokyo 3.webp",
        img_4: "king of tokyo 4.webp",
        img_5: "king of tokyo 5.webp",
        link: "king_of_tokyo",
        descripcion: "Los jugadores toman el control de monstruos gigantes que luchan por dominar la ciudad de Tokio, utilizando dados y cartas de poder para ganar. Cada turno, los jugadores lanzan dados personalizados para obtener energía, ataques, puntos de victoria y curación. Pueden usar la energía para comprar cartas de poder, que les otorgan habilidades especiales y ventajas estratégicas. El objetivo es ser el último monstruo en pie o alcanzar 20 puntos de victoria, utilizando tácticas inteligentes y ataques devastadores para eliminar a los rivales.",       
        jugadoresMinimos: 2, 
        jugadoresMaximos: 6, 
        duracionPartida: 40, 
        complejidad: 1, 
        precio: 150000 
    },
    { 
        nombre: "Kingdomino",          
        img_1: "kingdomino 1.webp",
        img_2: "kingdomino 2.jpg",
        img_3: "kingdomino 3.jpg",
        img_4: "kingdomino 4.jpg",
        link: "kingdomino",
        descripcion: "Kingdomino es un juego de mesa que combina la simplicidad de los dominós con la emoción de construir tu propio reino. En este juego, los jugadores deben explorar y expandir su territorio eligiendo fichas de dominó que representan diferentes tipos de terreno, como bosques, lagos, prados y campos de trigo. Cada ficha tiene dos secciones, y los jugadores deben conectar terrenos del mismo tipo para maximizar sus puntos. El juego se desarrolla por turnos, y la elección de la ficha es crucial, ya que determina no solo qué terrenos añadirás a tu reino, sino también el orden de colocación para la siguiente ronda. Al final de la partida, se puntúa cada reino multiplicando el número de cuadrados de cada tipo de terreno por el número de coronas presentes en esos terrenos. El jugador con la puntuación total más alta al final de la partida se alza con la victoria y es coronado como el mejor gobernante. Kingdomino es un juego que ofrece una experiencia de juego ágil y emocionante, ideal para veladas de juegos íntimas o reuniones familiares.",          
        jugadoresMinimos: 2, 
        jugadoresMaximos: 4, 
        duracionPartida: 25, 
        complejidad: 1, 
        precio: 35000 
    },
    { 
        nombre: "Paleo",               
        img_1: "paleo 1.jpg",
        img_2: "paleo 2.webp",
        img_3: "paleo 3.jpg",
        img_4: "paleo 4.webp",
        link: "paleo",   
        descripcion: "Paleo es un juego de mesa cooperativo que transporta a los jugadores a la Edad de Piedra, donde deben trabajar juntos para explorar, recolectar recursos y enfrentar desafíos en un entorno hostil. Cada turno, los jugadores eligen cartas de exploración sin conocer su contenido exacto, lo que añade un elemento de estrategia y sorpresa. El objetivo es sobrevivir y completar la pintura rupestre de la tribu, obteniendo fichas de victoria antes de acumular demasiadas fichas de cráneo, que representan el peligro y la pérdida de miembros de la tribu.",            
        jugadoresMinimos: 2, 
        jugadoresMaximos: 4, 
        duracionPartida: 60, 
        complejidad: 3, 
        precio: 90000 
    },
    { 
        nombre: "Pandemic",            
        img_1: "pandemic 1.webp",
        img_2: "pandemic 2.jfif",
        img_3: "pandemic 3.jpg",
        img_4: "pandemic 4.jpg",            
        link: "pandemic",
        descripcion: "En Pandemic, los jugadores forman parte de un equipo de especialistas que debe detener la propagación de cuatro enfermedades mortales que amenazan con infectar al mundo entero. El tablero muestra un mapa con ciudades conectadas, y las enfermedades se representan mediante cubos de colores que se van colocando en esas ciudades.",            
        jugadoresMinimos: 2, 
        jugadoresMaximos: 4, 
        duracionPartida: 60, 
        complejidad: 2, 
        precio: 120000 
    },
    { 
        nombre: "The Island",          
        img_1: "the island 1.jpg",
        img_2: "the island 2.webp",
        img_3: "the island 3.webp",
        img_4: "the island 4.webp", 
        img_5: "the island 5.jfif",          
        link: "the_island",    
        descripcion: "Los jugadores se convierten en exploradores y cada uno de ellos debe dirigir a su propio equipo de aventureros para salir de una isla cargados con los tesoros que en ella se encuentran. El objetivo es conseguir que el equipo llegue a tierra firme con la mayor cantidad de tesoros posible. Salir de la isla no es fácil, ya que un volcán dormido despierta y entra en erupción, hundiendo la isla. Los jugadores deben demostrar su instinto de supervivencia y enfrentar otros peligros, como monstruos marinos, tiburones y ballenas.",      
        jugadoresMinimos: 2, 
        jugadoresMaximos: 4, 
        duracionPartida: 45, 
        complejidad: 1, 
        precio: 117000 
    },
    { 
        nombre: "Truco",               
        img_1: "truco 1.jpg",
        img_2: "truco 2.jpg",
        img_3: "truco 3.png",              
        link: "truco", 
        descripcion: "El Truco es un juego de cartas que se juega con una baraja española de 40 cartas, excluyendo los 8, 9 y los comodines. El objetivo del juego es ganar un número determinado de chicos, que pueden ser de 1, 2 o 3. Cada chico se puede jugar a 15 o 30 puntos, y los puntos se suman al ganar una ronda, al ganar al truco o al envido. El juego se juega de a mano, donde cada jugador tira una carta y se reparten 3 cartas a cada jugador. El jugador que tira la carta más fuerte gana la mano y es el que comienza tirando la siguiente. Si hay empate, el jugador que es mano comienza la siguiente mano. El juego se divide en tres grandes cantos que suman puntos extra si se ganan.",              
        jugadoresMinimos: 2, 
        jugadoresMaximos: 6, 
        duracionPartida: 30, 
        complejidad: 1, 
        precio: 4000 
    },
];